### PR TITLE
fix test food to eat issue and api food to eat string name

### PR DESCRIPTION
**Pull request by Suabd**
Hello
I fixed the test food to eat because it wasn't working the one before. Also, I updated api_food_to eat.
Tell me if it needs any changes, Thanks!

### CODE REVIEW

**Review by JoshuaMathews — COMMENTED** [review]
So `convert_restaurant_name_to_str` method was added but it isn't used anywhere? I'm confused by that

**Comment by Suabd** [comment]
> So `convert_restaurant_name_to_str` method was added but it isn't used anywhere? I'm confused by that

Daniel Smeiska told me to make the "Restaurant name into string".

**Comment by sndmnska** [comment]
> > So `convert_restaurant_name_to_str` method was added but it isn't used anywhere? I'm confused by that
> 
> Daniel Smeiska told me to make the "Restaurant name into string".

That is true, from an older conversation.  I'm going to keep the method in there even though it's not used yet. It might be useful in fully constructing `main.py`.    I'm gonna give my approval and merge.

**Review by sndmnska — APPROVED** [review]
Looking good, thanks!

**Review by JoshuaMathews — APPROVED** [review]
Looks good to me!

**Comment by Spillahm** [comment]
looks fine

**Pull request merged**
